package ui

import "fmt"

// helpContent returns the help popup's rows, ported from tuicr's help
// sections.
//
// Every key the keymap dispatches should appear here; a test walks the
// keymap and fails when one does not, which is how this file stopped
// drifting behind the bindings.
func helpContent(leader rune) []string {
	l := string(leader)
	return []string{
		" Help (j/k scroll, / search) — press ? or Esc to close",
		"",
		" Navigation",
		"  j/k         move cursor down/up",
		"  Ctrl-d/u    half page down/up",
		"  Ctrl-f/b    full page down/up",
		"  Ctrl-e/y    scroll view without moving cursor",
		"  g/G         top / bottom ({N}G jumps to source line N)",
		"  zz/zt/zb    center / top / bottom cursor",
		"  }/{         next/previous file",
		"  ]/[         next/previous hunk",
		"  m/M         next/previous comment",
		"  (/)         previous/next commit (multi-commit reviews)",
		"  h/l         scroll horizontally",
		"  Enter/Space expand/collapse hidden context",
		"",
		" Panels",
		"  Tab/S-Tab   cycle focus through the visible panes",
		fmt.Sprintf("  %se          toggle the file list", l),
		fmt.Sprintf("  %sh/%sl       focus file list / diff", l, l),
		fmt.Sprintf("  %sj/%sk       focus down / up the layout", l, l),
		fmt.Sprintf("  %ss          toggle the commit selector", l),
		fmt.Sprintf("  %sf          toggle single-file view", l),
		"",
		" Leaving a review",
		fmt.Sprintf("  %st          back to the target selector", l),
		fmt.Sprintf("  %sp          back to the merge-request list", l),
		"  Esc         back to the selector when nothing is loaded",
		"",
		" File tree",
		"  Enter       open file / toggle directory",
		"  o/O         expand / collapse all directories",
		"",
		" Review",
		"  r           toggle file reviewed",
		"  R           toggle hunk reviewed",
		"  c           comment on the line at the cursor",
		"  C           comment on the file",
		fmt.Sprintf("  %sc          comment on the whole review", l),
		"  v/V         visual select (c comments the range, y yanks it)",
		"  i/A         edit the comment at the cursor (start / end)",
		"  dd          delete the comment at the cursor",
		"  y           yank the selection, or export the review",
		"",
		" Comment box",
		"  Enter       save          Shift-Enter  newline",
		"  Ctrl-s      save          Esc          cancel",
		"  Tab/S-Tab   cycle comment type",
		"  :vim        modal editing (then :w saves, :q cancels)",
		"",
		" Search",
		"  /           search",
		"  n/N         next / previous match",
		"",
		" Mouse",
		"  wheel       scroll the pane under the pointer",
		"  click       jump to a file, line, comment or commit",
		"  drag        select in the diff, then y to copy",
		"",
		" Commands",
		"  :q :q! :w :wq          quit / force quit / write / write-quit",
		"  :e :reload             re-read the diff (refetches a merge request)",
		"  :edit                  open the focused file in $EDITOR",
		"  :patches               review target selector, Patches tab",
		"  :clip :export          copy the review to the clipboard",
		"  :patch :reply          copy the review as a quoted-diff mail reply",
		"  :clear :clearc         clear comments (and reviewed marks)",
		"  :diff                  unified / side-by-side",
		"  :wrap :set wrap!       toggle line wrap",
		"  :focus :f              toggle single-file view",
		"  :stage                 stage reviewed files (git)",
		"  :commits :targets      open the target selector",
		"  :prs                   open the merge-request list",
		"  :set commits[!]        show / toggle the commit selector",
		"  :comments unresolved|all|hide   existing forge comments",
		"  :submit [comment|approve|request-changes|draft]",
		"  :{N} :o{N}             jump to line N (new / old side)",
		"  :version               show the build",
		"  :agent :agent off      show / revoke the agent-submit grant",
		"",
		" Quit",
		"  q           quit    ZZ/ZQ  quit           Ctrl-C twice  force quit",
	}
}
